default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: user_1
  password: 123456
  
development:
  <<: *default
  database: mob_shopping_development

test:
  <<: *default
  database: mob_shopping_test

production:
  <<: *default
  database: mob_shopping_production